package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.MenuButton;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

import ?;

public class FacturacionController {
	@FXML
	private MenuButton tipoPagoMenu;
	@FXML
	private TextField cedulaClienteText;
	@FXML
	private TextField referenciaText;
	@FXML
	private TextField numeroFcaturaText;
	@FXML
	private TextField nombreClienteText;
	@FXML
	private TextField totalPagoText;
	@FXML
	private TableView Tablaview;
	@FXML
	private TableColumn ReferenciaColumn;
	@FXML
	private TableColumn DescripcionColumn;
	@FXML
	private TableColumn CategoriaColumn;
	@FXML
	private TableColumn CantidadColumn;
	@FXML
	private TableColumn ValorUColumn;
	@FXML
	private TableColumn ValorTColumn;
	@FXML
	private TextField cantidadText;
	@FXML
	private ImageView btnCerrar;
	@FXML
	private Button buscarBtn;
	@FXML
	private Button generarBtn;
	@FXML
	private Button eliminarBtn;
	@FXML
	private Button actualizarBtn;

	// Event Listener on TableColumn[#ReferenciaColumn].onEditCommit
	@FXML
	public void ReferenciaColumn(? event) {
		// TODO Autogenerated
	}
	// Event Listener on TableColumn[#DescripcionColumn].onEditCommit
	@FXML
	public void DescripcionColumn(? event) {
		// TODO Autogenerated
	}
	// Event Listener on TableColumn[#CategoriaColumn].onEditCommit
	@FXML
	public void CategoriaColumn(? event) {
		// TODO Autogenerated
	}
	// Event Listener on TableColumn[#CantidadColumn].onEditCommit
	@FXML
	public void CantidadColumn(? event) {
		// TODO Autogenerated
	}
	// Event Listener on TableColumn[#ValorUColumn].onEditCommit
	@FXML
	public void ValorUColumn(? event) {
		// TODO Autogenerated
	}
	// Event Listener on TableColumn[#ValorTColumn].onEditCommit
	@FXML
	public void ValorTColumn(? event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#btnCerrar].onMouseClicked
	@FXML
	public void btnCerrar(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#buscarBtn].onMouseClicked
	@FXML
	public void buscarBtn(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#generarBtn].onMouseClicked
	@FXML
	public void generarBtn(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarBtn].onMouseClicked
	@FXML
	public void eliminarBtn(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#actualizarBtn].onMouseClicked
	@FXML
	public void actualizarBtn(MouseEvent event) {
		// TODO Autogenerated
	}
}
