package application;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class vistaBotonesController {
	@FXML
	private ImageView btnFacturacion;
	@FXML
	private ImageView btnClientes;
	@FXML
	private ImageView btnProductos;
	@FXML
	private ImageView btnUsuarios;
	@FXML
	private ImageView btnInformes;

	// Event Listener on ImageView[#btnFacturacion].onMouseClicked
	@FXML
	public void btnFacturacion(MouseEvent event) throws IOException {
		
		System.out.println("abrir facturacion");
		FXMLLoader loader = new FXMLLoader(getClass().getResource("vista2.fxml"));
        Stage stage = new Stage();
		stage.setScene(new Scene(loader.load()));
        stage.show();
     	return;
		
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#btnClientes].onMouseClicked
	@FXML
	public void btnClientes(MouseEvent event) throws IOException {
		
		System.out.println("abrir clientes");
		FXMLLoader loader = new FXMLLoader(getClass().getResource("vista3.fxml"));
        Stage stage = new Stage();
		stage.setScene(new Scene(loader.load()));
        stage.show();
     	return;
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#btnProductos].onMouseClicked
	@FXML
	public void btnProductos(MouseEvent event) throws IOException {
		
		System.out.println("abrir productos");
		FXMLLoader loader = new FXMLLoader(getClass().getResource("vista5.fxml"));
        Stage stage = new Stage();
		stage.setScene(new Scene(loader.load()));
        stage.show();
     	return;
		
		
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#btnUsuarios].onMouseClicked
	@FXML
	public void btnUsuarios(MouseEvent event) throws IOException {
		System.out.println("abrir usuairos");
		FXMLLoader loader = new FXMLLoader(getClass().getResource("vista4.fxml"));
        Stage stage = new Stage();
		stage.setScene(new Scene(loader.load()));
        stage.show();
     	return;
     	}
	// Event Listener on ImageView[#btnInformes].onMouseClicked
	@FXML
	public void btnInformes(MouseEvent event) throws IOException {
		
		System.out.println("abrir informes");
		FXMLLoader loader = new FXMLLoader(getClass().getResource("vista6.fxml"));
        Stage stage = new Stage();
		stage.setScene(new Scene(loader.load()));
        stage.show();
     	return;
		
		
		// TODO Autogenerated
	}


	public void btnCerrar(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("cerrar");
	}
}
